;;; denote-menu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from denote-menu.el

(autoload 'denote-menu-list-notes "denote-menu" "\
Display list of Denote files in variable `denote-directory'." t)
(register-definition-prefixes "denote-menu" '("denote-menu-" "list-denotes"))

;;; End of scraped data

(provide 'denote-menu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-menu-autoloads.el ends here
